### ISSUE TITLE
Player Video MacOS

### ISSUE THREAD

**Issue by mauromarzocca** [fexh10/aw-cli#11]
Ciao a tutti, ho configurato su MacOS lo script, ma non viene aperto il player video. 
Ho configurato VLC tramite `aw-cli -a` ma senza alcun successo.
Potreste aiutarmi?

**Comment by fexh10** [comment]
Ciao. Per configurare il player, dovresti inserire il percorso di VLC quando viene richiesto "Inserisci il path del player". Su MacOS penso che sia `/Applications/VLC.app/Contents/MacOS/VLC`

**Comment by fexh10** [comment]
Non avendo ricevuto alcuna risposta o aggiornamento su questa issue per un periodo prolungato, la chiudo
