### ISSUE TITLE
Domanda

### ISSUE THREAD

**Issue by GioGio03** [fexh10/aw-cli#3]
Siccome non uso python vorrei sapere se hai fatto una sorta di web scraping da aniList o se hai usato un API

**Comment by fexh10** [comment]
Per quanto riguarda AniList utilizziamo le Api, altrimenti non sarebbe possibile modificare i dati nella watchlist dell'utente. Per AnimeWorld, invece, è semplice web scraping.

**Comment by NotSoMik** [comment]
@fexh10 puoi mandarmi l'api che usate che non la trovo nel codice dato che non me ne intendo molto

**Comment by fexh10** [comment]
@NotSoMik C'è una guida abbastanza dettagliata su come usare le API di AniList, la puoi trovare [qua](https://anilist.gitbook.io/anilist-apiv2-docs/overview/graphql/getting-started).

**Comment by NotSoMik** [comment]
Non so se siete in due o più persone ma nel caso usate solo python perché io e un gruppo di dev non italiani dovremmo iniziare a progettare un sito streaming anime con nextjs e dotnet quindi vorrei sapere se potreste essere interessati @fexh10

**Comment by fexh10** [comment]
@NotSoMik Purtroppo sono linguaggi che non conosco

**Comment by NotSoMik** [comment]
@fexh10 ah ok, vabbè fa nulla, hai discord? Così posso chiederti più informazioni riguardo questo progetto

**Comment by fexh10** [comment]
@NotSoMik Sì, stesso nick di github

**Comment by NotSoMik** [comment]
@fexh10 okay ti ho mandato la richiesta
