### ISSUE TITLE
Problema nell' installazione su Termux

### ISSUE THREAD

**Issue by 45IF** [fexh10/aw-cli#8]
![Screenshot_2024-02-16-15-47-21-620_com termux](https://github.com/fexh10/aw-cli/assets/118003830/05029086-8392-4036-9f24-4c8b3bf31912)

**Comment by fexh10** [comment]
Penso che installando i seguenti pacchetti: `pkg install libxml2 libxslt pkg-config` si debba riuscire a risolvere l'errore

**Comment by 45IF** [comment]
> Penso che installando i seguenti pacchetti: `pkg install libxml2 libxslt pkg-config` si debba riuscire a risolvere l'errore

Grazie mille adesso funziona
